//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent.InputData", typeof(InputData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 156
        ///153
        ///163
        ///168
        ///166
        ///164
        ///149
        ///187
        ///192
        ///194
        ///197
        ///199
        ///201
        ///210
        ///211
        ///196
        ///202
        ///203
        ///193
        ///199
        ///236
        ///240
        ///241
        ///251
        ///228
        ///226
        ///227
        ///256
        ///269
        ///270
        ///265
        ///271
        ///267
        ///271
        ///247
        ///254
        ///259
        ///258
        ///269
        ///270
        ///269
        ///267
        ///289
        ///290
        ///288
        ///309
        ///307
        ///299
        ///309
        ///326
        ///329
        ///332
        ///335
        ///338
        ///342
        ///333
        ///330
        ///332
        ///333
        ///334
        ///318
        ///317
        ///318
        ///316
        ///314
        ///315
        ///322
        ///327
        ///328
        ///331
        ///332
        ///338
        ///346
        ///341
        ///350
        ///334
        ///323
        ///322
        ///321
        ///325
        ///329
        ///342
        ///343
        ///353
        ///361
        ///355
        ///331
        ///329
        ///330
        ///319
        ///321
        ///322
        ///321
        ///322
        ///325
        ///316
        ///317
        ///322
        ///324
        ///331
        ///322
        ///323
        ///32 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01Sonar {
            get {
                return ResourceManager.GetString("Day01Sonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 1
        ///forward 2
        ///down 5
        ///down 5
        ///down 4
        ///down 9
        ///up 6
        ///up 7
        ///down 2
        ///forward 9
        ///up 4
        ///forward 7
        ///forward 9
        ///up 3
        ///down 1
        ///forward 5
        ///down 3
        ///forward 3
        ///forward 3
        ///forward 3
        ///down 2
        ///down 5
        ///forward 7
        ///down 7
        ///up 7
        ///down 9
        ///down 1
        ///down 4
        ///down 9
        ///down 2
        ///forward 2
        ///forward 4
        ///up 7
        ///up 1
        ///forward 3
        ///forward 8
        ///forward 9
        ///forward 6
        ///forward 9
        ///forward 1
        ///forward 5
        ///down 9
        ///up 7
        ///down 9
        ///forward 2
        ///forward 9
        ///forward 1
        ///forward 5
        ///up 8
        ///down 5
        ///forward 4
        ///up 6
        ///up 9
        ///forward 2
        ///up 8
        ///down 1
        ///up 5
        ///forward [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02Dive {
            get {
                return ResourceManager.GetString("Day02Dive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 110001010111
        ///011011110010
        ///110011110011
        ///101000010111
        ///011101100100
        ///111001011100
        ///011100000101
        ///011110110011
        ///001001111111
        ///111000010000
        ///001000101100
        ///011100111010
        ///011100111000
        ///011100010001
        ///100001100000
        ///111010111110
        ///100011000101
        ///010111000101
        ///100110110011
        ///101010110011
        ///110101110010
        ///110111100010
        ///000001100100
        ///010010011010
        ///001001001100
        ///101000000111
        ///100100110011
        ///111111100011
        ///110010001010
        ///100010110011
        ///111101101001
        ///101001001101
        ///110111011101
        ///100100101101
        ///111111000011
        ///001110010110
        ///01011011 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03Report {
            get {
                return ResourceManager.GetString("Day03Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26,38,2,15,36,8,12,46,88,72,32,35,64,19,5,66,20,52,74,3,59,94,45,56,0,6,67,24,97,50,92,93,84,65,71,90,96,21,87,75,58,82,14,53,95,27,49,69,16,89,37,13,1,81,60,79,51,18,48,33,42,63,39,34,62,55,47,54,23,83,77,9,70,68,85,86,91,41,4,61,78,31,22,76,40,17,30,98,44,25,80,73,11,28,7,99,29,57,43,10
        ///
        ///57 12 60 96 93
        ///73 87 63 70 91
        ///74 32 43 67 46
        ///59 34  5 35 82
        ///53 40 55 29  1
        ///
        ///48 71 59 45 63
        ///13 42 23 95 39
        ///84 82 10 29  4
        ///16 91 32 92 62
        ///99 33 20 21  3
        ///
        ///51 20 32 30 90
        ///86 88 89  1 73
        /// 5 64 78 81 22
        ///95 50   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04Squid {
            get {
                return ResourceManager.GetString("Day04Squid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 657,934 -&gt; 657,926
        ///130,34 -&gt; 570,474
        ///478,716 -&gt; 226,464
        ///861,110 -&gt; 861,167
        ///448,831 -&gt; 370,831
        ///75,738 -&gt; 390,738
        ///26,880 -&gt; 864,42
        ///965,658 -&gt; 527,220
        ///208,381 -&gt; 80,381
        ///523,475 -&gt; 807,475
        ///219,69 -&gt; 219,434
        ///793,538 -&gt; 534,797
        ///754,602 -&gt; 754,148
        ///443,327 -&gt; 443,611
        ///606,395 -&gt; 546,395
        ///980,56 -&gt; 51,985
        ///619,325 -&gt; 354,325
        ///342,123 -&gt; 819,600
        ///290,533 -&gt; 374,533
        ///598,77 -&gt; 598,75
        ///605,302 -&gt; 605,636
        ///97,981 -&gt; 692,386
        ///278,779 -&gt; 278,800
        ///661,377 -&gt; 661,10
        ///726,108 -&gt; 518,316
        ///271,883 -&gt; 271,50
        ///382,2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day05Vent {
            get {
                return ResourceManager.GetString("Day05Vent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5,3,2,2,1,1,4,1,5,5,1,3,1,5,1,2,1,4,1,2,1,2,1,4,2,4,1,5,1,3,5,4,3,3,1,4,1,3,4,4,1,5,4,3,3,2,5,1,1,3,1,4,3,2,2,3,1,3,1,3,1,5,3,5,1,3,1,4,2,1,4,1,5,5,5,2,4,2,1,4,1,3,5,5,1,4,1,1,4,2,2,1,3,1,1,1,1,3,4,1,4,1,1,1,4,4,4,1,3,1,3,4,1,4,1,2,2,2,5,4,1,3,1,2,1,4,1,4,5,2,4,5,4,1,2,1,4,2,2,2,1,3,5,2,5,1,1,4,5,4,3,2,4,1,5,2,2,5,1,4,1,5,1,3,5,1,2,1,1,1,5,4,4,5,1,1,1,4,1,3,3,5,5,1,5,2,1,1,3,1,1,3,2,3,4,4,1,5,5,3,2,1,1,1,4,3,1,3,3,1,1,2,2,1,2,2,2,1,1,5,1,2,2,5,2,4,1,1,2,4,1,2,3,4,1,2,1,2,4,2,1,1,5,3,1,4,4,4,1,5,2,3,4,4,1,5, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day06Fish {
            get {
                return ResourceManager.GetString("Day06Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1101,1,29,67,1102,0,1,65,1008,65,35,66,1005,66,28,1,67,65,20,4,0,1001,65,1,65,1106,0,8,99,35,67,101,99,105,32,110,39,101,115,116,32,112,97,115,32,117,110,101,32,105,110,116,99,111,100,101,32,112,114,111,103,114,97,109,10,760,1085,275,960,23,133,190,86,999,298,714,247,509,704,122,1109,713,51,41,1028,59,10,251,0,600,201,103,176,482,204,747,540,57,33,133,90,724,793,294,1618,762,65,1579,4,603,1182,25,12,718,30,1534,614,1021,1175,20,647,201,65,136,798,526,1,1060,70,329,194,54,747,423,349,261,604,133,32,1074,148, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day07Crabs {
            get {
                return ResourceManager.GetString("Day07Crabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dacefg fegab de dceb bedag dae bcgaefd bdacg fbgcad bgedca | acfebgd de dbagc deagcb
        ///cfgda fdebgc bfcdeag dbg afgedb efbad bg cdfeab gabdf abeg | dbg fbedgca gbea gbae
        ///dgcbe egdafcb bgcfe dgbf cgbafe db ecbfad deb agcde gdbfec | edb bcefgd gdfb edb
        ///fbgad bgedafc dcageb gcfbed bgdfca ebfag df fdg fcad bcagd | gdecfb dbfgac cgabd fd
        ///bacgd dbceg acedgf dgefb dcfbag cgbead edc ce abce bgecfad | abec gdcfea cbdga agbcde
        ///gcbfde gbdfeca ec afcbge egafb cdagb dbegfa ecaf bcaeg egc | egfcdb cgbdfe ebafgc cdfgeb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day08Segment {
            get {
                return ResourceManager.GetString("Day08Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3235678976543234569109899875456987676387679999878953234987656895457998743212347892123999912987632489
        ///2124899989932145698998789994329876545235567899768995349898546789346987654423656789339889899986541678
        ///1012567897898756797987678989212985432103458987656789456789435691235998775634987897998776798775430567
        ///2343489956789987976798899578901299654512578998545899567894326890449899896845898945899655987654321378
        ///3455697645678999875679965467892398999323456789656798998952018921598799987896789235789544398765435459
        ///45 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day09Smoke {
            get {
                return ResourceManager.GetString("Day09Smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&lt;&lt;&lt;{&lt;&lt;&lt;(&lt;&lt;(([]())(&lt;&gt;&lt;&gt;))&lt;[{}()][(){}]&gt;&gt;(([()[]]&lt;{}()&gt;)[&lt;[]{}&gt;[(){}]])&gt;)&gt;([{&lt;&lt;&lt;()()&gt;[&lt;&gt;()
        ///[&lt;[&lt;{[[({[({{[(){}][()[]]}&lt;[{}&lt;&gt;](&lt;&gt;[])&gt;}{&lt;[{}{}][&lt;&gt;()]]{{[]}{[][]}}}){(([&lt;&gt;{}]&lt;(){}&gt;))&lt;({&lt;&gt;{}}{{}{}}){[[]&lt;&gt;
        ///[&lt;&lt;&lt;[{{[[{({{[&lt;&gt;{}][()]}}[[[[][]][{}&lt;&gt;]]])&lt;{(({}&lt;&gt;)&lt;()&gt;)&lt;[{}&lt;&gt;][()()]&gt;}&gt;}(&lt;{[[()()]{{}()}]&gt;[&lt;&lt;{}
        ///([[{&lt;{{({&lt;[{[([][]){[]&lt;&gt;}&gt;(&lt;[][]&gt;[&lt;&gt;()])}([&lt;&lt;&gt;&gt;&lt;{}&lt;&gt;&gt;]{({}{})[{}[]]})]&gt;})[[[&lt;&lt;(&lt;()[]&gt;{&lt;&gt;()
        ///{([&lt;(({[[&lt;{{[[{}&lt;&gt;]({}[])&gt;&lt;{(){}}{()()}&gt;}&lt;&lt;[()[]][{}[]]&gt;&lt;[&lt;&gt;{}]([]{})&gt;&gt;}([(&lt;(){}&gt;{{}()})&lt;&lt;{}{}&gt;{[]{
        ///[[(&lt;{[&lt;(&lt;&lt;([&lt;{&lt;&gt;()} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day10Syntax {
            get {
                return ResourceManager.GetString("Day10Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8271653836
        ///7567626775
        ///2315713316
        ///6542655315
        ///2453637333
        ///1247264328
        ///2325146614
        ///2115843171
        ///6182376282
        ///2384738675.
        /// </summary>
        internal static string Day11Octopus {
            get {
                return ResourceManager.GetString("Day11Octopus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ma-start
        ///YZ-rv
        ///MP-rv
        ///vc-MP
        ///QD-kj
        ///rv-kj
        ///ma-rv
        ///YZ-zd
        ///UB-rv
        ///MP-xe
        ///start-MP
        ///zd-end
        ///ma-UB
        ///ma-MP
        ///UB-xe
        ///end-UB
        ///ju-MP
        ///ma-xe
        ///zd-UB
        ///start-xe
        ///YZ-end.
        /// </summary>
        internal static string Day12Caves {
            get {
                return ResourceManager.GetString("Day12Caves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1284,229
        ///713,50
        ///1267,194
        ///437,229
        ///651,200
        ///763,407
        ///1173,373
        ///248,579
        ///503,395
        ///155,532
        ///278,488
        ///863,444
        ///403,695
        ///20,25
        ///709,105
        ///1063,560
        ///554,94
        ///955,444
        ///897,813
        ///792,665
        ///969,799
        ///1293,843
        ///261,716
        ///1084,542
        ///33,579
        ///1295,656
        ///82,743
        ///1101,789
        ///164,506
        ///856,220
        ///199,323
        ///252,733
        ///525,669
        ///1292,137
        ///1230,756
        ///552,856
        ///1120,229
        ///59,42
        ///360,737
        ///346,215
        ///1005,285
        ///673,535
        ///1150,131
        ///540,177
        ///822,539
        ///301,375
        ///410,743
        ///1303,357
        ///1290,540
        ///873,574
        ///551,434
        ///875,86
        ///300,336
        ///301,560
        ///373,184
        ///1125,460
        ///8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day13Origami {
            get {
                return ResourceManager.GetString("Day13Origami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOBFPNOPBHKCCVHOBCSO
        ///
        ///NS -&gt; H
        ///NN -&gt; P
        ///FF -&gt; O
        ///HF -&gt; C
        ///KN -&gt; V
        ///PO -&gt; B
        ///PS -&gt; B
        ///FB -&gt; N
        ///ON -&gt; F
        ///OK -&gt; F
        ///OO -&gt; K
        ///KS -&gt; F
        ///FN -&gt; F
        ///KC -&gt; H
        ///NC -&gt; N
        ///NB -&gt; C
        ///KH -&gt; S
        ///SV -&gt; B
        ///BC -&gt; S
        ///KB -&gt; B
        ///SC -&gt; S
        ///KP -&gt; H
        ///FS -&gt; K
        ///NK -&gt; K
        ///OC -&gt; H
        ///NH -&gt; C
        ///PH -&gt; F
        ///OS -&gt; V
        ///BB -&gt; C
        ///CC -&gt; F
        ///CF -&gt; H
        ///CP -&gt; V
        ///VB -&gt; N
        ///VC -&gt; F
        ///PK -&gt; V
        ///NV -&gt; N
        ///FO -&gt; S
        ///CK -&gt; O
        ///BH -&gt; K
        ///PN -&gt; B
        ///PP -&gt; S
        ///NF -&gt; B
        ///SF -&gt; K
        ///VF -&gt; H
        ///HS -&gt; F
        ///NP -&gt; F
        ///SH -&gt; V
        ///SK -&gt; K
        ///PC -&gt; V
        ///BO -&gt; H
        ///HN -&gt; P
        ///BK -&gt; O
        ///BP -&gt; S
        ///OP -&gt; N
        ///SP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day14Polymer {
            get {
                return ResourceManager.GetString("Day14Polymer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6851182918317729984894479998919639588287499951229786985839869531985173849166964176451789434892199898
        ///9426994946481789516799194682986158574783332188959768397416981269349655657969713682881596193639995681
        ///3796886996869882629998132915973989548786867985998963691489853939899277919988858417991899981198719977
        ///9248185139261798695718986776781989149442673212774599795188279468121787972899969696979856585911949398
        ///6299473779566125911813915682136997199718287928169899397951248974185914193847568951998753279193952849
        ///81 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day15Chiton {
            get {
                return ResourceManager.GetString("Day15Chiton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E20D72805F354AE298E2FCC5339218F90FE5F3A388BA60095005C3352CF7FBF27CD4B3DFEFC95354723006C401C8FD1A23280021D1763CC791006E25C198A6C01254BAECDED7A5A99CCD30C01499CFB948F857002BB9FCD68B3296AF23DD6BE4C600A4D3ED006AA200C4128E10FC0010C8A90462442A5006A7EB2429F8C502675D13700BE37CF623EB3449CAE732249279EFDED801E898A47BE8D23FBAC0805527F99849C57A5270C064C3ECF577F4940016A269007D3299D34E004DF298EC71ACE8DA7B77371003A76531F20020E5C4CC01192B3FE80293B7CD23ED55AA76F9A47DAAB6900503367D240522313ACB26B8801B64CDB1FB683A6E50E0049BE4F6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day16Packets {
            get {
                return ResourceManager.GetString("Day16Packets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target area: x=281..311, y=-74..-54.
        /// </summary>
        internal static string Day17Target {
            get {
                return ResourceManager.GetString("Day17Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[[6,6],3],0]
        ///[[[0,[9,9]],[[7,7],[4,6]]],[[5,6],[5,9]]]
        ///[[[1,[6,5]],7],[[6,[3,6]],5]]
        ///[[0,[9,[0,2]]],[[[1,9],3],[[0,1],[5,1]]]]
        ///[[[3,[7,6]],[1,0]],[[4,[7,9]],[5,4]]]
        ///[[0,9],[[[0,3],[2,9]],3]]
        ///[[[[3,2],0],[7,6]],[9,[[4,6],0]]]
        ///[[4,[[2,5],[4,0]]],[2,[8,[3,0]]]]
        ///[[[[3,5],6],[[8,6],2]],[[6,[5,1]],[[1,0],[3,2]]]]
        ///[[1,[[2,8],[2,9]]],[[7,[8,8]],[[2,1],[9,5]]]]
        ///[[[4,[4,6]],[[5,7],4]],[8,0]]
        ///[[[3,[5,9]],[1,[6,5]]],[1,9]]
        ///[[[5,7],[4,1]],4]
        ///[3,[[6,0],[[9,0],[8,2]]]]
        ///[[7,[[5,4],[7,3]]],[6,[[9,0],[1,9]]]]        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day18Snailfish {
            get {
                return ResourceManager.GetString("Day18Snailfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- scanner 0 ---
        ///615,499,683
        ///-748,-781,588
        ///392,-638,-524
        ///-453,892,-689
        ///-127,159,-103
        ///-782,-721,695
        ///793,523,765
        ///558,953,-776
        ///-960,-476,-523
        ///620,476,721
        ///748,920,-718
        ///-389,915,-762
        ///-885,-408,-561
        ///-647,775,719
        ///266,-564,461
        ///-396,937,-868
        ///270,-648,-624
        ///-608,-779,712
        ///338,-641,-737
        ///254,-682,345
        ///274,-501,402
        ///-729,775,740
        ///-932,-413,-581
        ///-673,894,662
        ///797,944,-790
        ///7,45,10
        ///
        ///--- scanner 1 ---
        ///741,375,-668
        ///-552,824,562
        ///476,379,502
        ///-428,760,-619
        ///-397,584,-575
        ///623,498,481
        ///-544,561,562
        ///-5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day19Scanner {
            get {
                return ResourceManager.GetString("Day19Scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ########..#..#.##.##.#.#..#.#.###.######.##..##.##..#...#....##.##...##.#.#...#.#.##.###.#.##.#.##.#...#.#.###.#.##.#.####.###..#.####.##..#.#####..####.#.#.#....##.#.#.##...#.####.#....#.##..##...#...#.##..#...#.#..#..#.#.#..##..#.##.##..##...#..###...##..#..###.###.##..#..#####...#.#..###..##....##...#####.#####...##.#.##.#....#.##.#.###.#.##.#.##...######.#...##.#..#.#.#...###.#..#.##.####..##.#..#.##.#.##.######.#.....#.#....####.####.###...#....#..###..###.#...#.#.#.##..#..##.#.#..#..###.#.###..#...... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day20Trench {
            get {
                return ResourceManager.GetString("Day20Trench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 1 starting position: 9
        ///Player 2 starting position: 6.
        /// </summary>
        internal static string Day21Dice {
            get {
                return ResourceManager.GetString("Day21Dice", resourceCulture);
            }
        }
    }
}
