//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent.InputData", typeof(InputData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 156
        ///153
        ///163
        ///168
        ///166
        ///164
        ///149
        ///187
        ///192
        ///194
        ///197
        ///199
        ///201
        ///210
        ///211
        ///196
        ///202
        ///203
        ///193
        ///199
        ///236
        ///240
        ///241
        ///251
        ///228
        ///226
        ///227
        ///256
        ///269
        ///270
        ///265
        ///271
        ///267
        ///271
        ///247
        ///254
        ///259
        ///258
        ///269
        ///270
        ///269
        ///267
        ///289
        ///290
        ///288
        ///309
        ///307
        ///299
        ///309
        ///326
        ///329
        ///332
        ///335
        ///338
        ///342
        ///333
        ///330
        ///332
        ///333
        ///334
        ///318
        ///317
        ///318
        ///316
        ///314
        ///315
        ///322
        ///327
        ///328
        ///331
        ///332
        ///338
        ///346
        ///341
        ///350
        ///334
        ///323
        ///322
        ///321
        ///325
        ///329
        ///342
        ///343
        ///353
        ///361
        ///355
        ///331
        ///329
        ///330
        ///319
        ///321
        ///322
        ///321
        ///322
        ///325
        ///316
        ///317
        ///322
        ///324
        ///331
        ///322
        ///323
        ///32 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01Sonar {
            get {
                return ResourceManager.GetString("Day01Sonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 1
        ///forward 2
        ///down 5
        ///down 5
        ///down 4
        ///down 9
        ///up 6
        ///up 7
        ///down 2
        ///forward 9
        ///up 4
        ///forward 7
        ///forward 9
        ///up 3
        ///down 1
        ///forward 5
        ///down 3
        ///forward 3
        ///forward 3
        ///forward 3
        ///down 2
        ///down 5
        ///forward 7
        ///down 7
        ///up 7
        ///down 9
        ///down 1
        ///down 4
        ///down 9
        ///down 2
        ///forward 2
        ///forward 4
        ///up 7
        ///up 1
        ///forward 3
        ///forward 8
        ///forward 9
        ///forward 6
        ///forward 9
        ///forward 1
        ///forward 5
        ///down 9
        ///up 7
        ///down 9
        ///forward 2
        ///forward 9
        ///forward 1
        ///forward 5
        ///up 8
        ///down 5
        ///forward 4
        ///up 6
        ///up 9
        ///forward 2
        ///up 8
        ///down 1
        ///up 5
        ///forward [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02Dive {
            get {
                return ResourceManager.GetString("Day02Dive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 110001010111
        ///011011110010
        ///110011110011
        ///101000010111
        ///011101100100
        ///111001011100
        ///011100000101
        ///011110110011
        ///001001111111
        ///111000010000
        ///001000101100
        ///011100111010
        ///011100111000
        ///011100010001
        ///100001100000
        ///111010111110
        ///100011000101
        ///010111000101
        ///100110110011
        ///101010110011
        ///110101110010
        ///110111100010
        ///000001100100
        ///010010011010
        ///001001001100
        ///101000000111
        ///100100110011
        ///111111100011
        ///110010001010
        ///100010110011
        ///111101101001
        ///101001001101
        ///110111011101
        ///100100101101
        ///111111000011
        ///001110010110
        ///01011011 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03Report {
            get {
                return ResourceManager.GetString("Day03Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26,38,2,15,36,8,12,46,88,72,32,35,64,19,5,66,20,52,74,3,59,94,45,56,0,6,67,24,97,50,92,93,84,65,71,90,96,21,87,75,58,82,14,53,95,27,49,69,16,89,37,13,1,81,60,79,51,18,48,33,42,63,39,34,62,55,47,54,23,83,77,9,70,68,85,86,91,41,4,61,78,31,22,76,40,17,30,98,44,25,80,73,11,28,7,99,29,57,43,10
        ///
        ///57 12 60 96 93
        ///73 87 63 70 91
        ///74 32 43 67 46
        ///59 34  5 35 82
        ///53 40 55 29  1
        ///
        ///48 71 59 45 63
        ///13 42 23 95 39
        ///84 82 10 29  4
        ///16 91 32 92 62
        ///99 33 20 21  3
        ///
        ///51 20 32 30 90
        ///86 88 89  1 73
        /// 5 64 78 81 22
        ///95 50   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04Squid {
            get {
                return ResourceManager.GetString("Day04Squid", resourceCulture);
            }
        }
    }
}
