//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent.InputData", typeof(InputData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 156
        ///153
        ///163
        ///168
        ///166
        ///164
        ///149
        ///187
        ///192
        ///194
        ///197
        ///199
        ///201
        ///210
        ///211
        ///196
        ///202
        ///203
        ///193
        ///199
        ///236
        ///240
        ///241
        ///251
        ///228
        ///226
        ///227
        ///256
        ///269
        ///270
        ///265
        ///271
        ///267
        ///271
        ///247
        ///254
        ///259
        ///258
        ///269
        ///270
        ///269
        ///267
        ///289
        ///290
        ///288
        ///309
        ///307
        ///299
        ///309
        ///326
        ///329
        ///332
        ///335
        ///338
        ///342
        ///333
        ///330
        ///332
        ///333
        ///334
        ///318
        ///317
        ///318
        ///316
        ///314
        ///315
        ///322
        ///327
        ///328
        ///331
        ///332
        ///338
        ///346
        ///341
        ///350
        ///334
        ///323
        ///322
        ///321
        ///325
        ///329
        ///342
        ///343
        ///353
        ///361
        ///355
        ///331
        ///329
        ///330
        ///319
        ///321
        ///322
        ///321
        ///322
        ///325
        ///316
        ///317
        ///322
        ///324
        ///331
        ///322
        ///323
        ///32 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01Sonar {
            get {
                return ResourceManager.GetString("Day01Sonar", resourceCulture);
            }
        }
    }
}
